name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Run tests for backend
        run: |
          cd backend
          npm test

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Run lint for frontend
        run: |
          cd frontend
          npm run lint

      - name: Run tests for frontend
        run: |
          cd frontend
          npm test
